# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bear', models.TextField()),
                ('StartLine', models.IntegerField()),
                ('StartLineURL', models.TextField()),
                ('EndLine', models.IntegerField()),
                ('EndLineURL', models.TextField()),
                ('Aspect', models.TextField()),
                ('Confidence', models.IntegerField()),
                ('DebugMsg', models.TextField()),
                ('Diffs', models.TextField()),
                ('BearId', models.TextField()),
                ('Message', models.TextField()),
                ('MessageArguments', models.TextField()),
                ('MessageBase', models.TextField()),
                ('Severity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('URL', models.TextField()),
                ('FilePath', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('URL', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='ProjectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project'),
        ),
        migrations.AddField(
            model_name='bear',
            name='FileName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.File'),
        ),
        migrations.AddField(
            model_name='bear',
            name='ProjectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analyzer.Project'),
        ),
    ]
